### ISSUE TITLE
Syntax error on line-breaked `let`

### ISSUE THREAD

**Issue by jrosain** [JonasHoefer/poset-type-theory#2]
The following code produces a syntax error on the `let ...` line when evaluating it.
```
bad (A : U) : U =
  let S : U =
    A in
  S -> S
```
I've run some more tests and I've found that the syntax here seems indentation-dependent (which is weird as it doesn't seem to be this way for others syntactical constructions):
```
-- does not work
bad' (A : U) : U =
  let S : U =
      A in
  S -> S

-- works
good (A : U) : U =
  let S : U =
        A in
  S -> S
```
Note that it behaves similarly if the `=` is on the second line:
```
-- does not work
bad'' (A : U) : U =
  let S : U
  = A in
  S -> S

-- works
good' (A : U) : U =
  let S : U
        = A in
  S -> S
```

**Comment by JonasHoefer** [comment]
The syntax is supposed to be indentation dependent and behave similar to Haskells. The parser is generated using [BNFC](https://hackage.haskell.org/package/BNFC) using the grammar in [sec/PosTT/Frontend/Exp.cf](https://github.com/JonasHoefer/poset-type-theory/blob/main/src/PosTT/Frontend/Exp.cf). The grammar is essentially the same as the one used for [cubical](https://github.com/simhu/cubical) and [cubicaltt](https://github.com/mortberg/cubicaltt/) and uses BNFCs mechanism for [indentation dependent syntax](https://bnfc.readthedocs.io/en/latest/lbnf.html#layout-syntax). I am unsure how your examples should behave and how customizable BNFCs mechanism is. The intended use is for `let` and `in` to be aligned, allowing code such as
```
let x : Nat = zero
    y : Nat = suc zero
in  plus x y
```
